### ISSUE TITLE
Crash on MacOS Catalina

### ISSUE THREAD

**Issue by NicolasDucom** [CircuitMess/CircuitBlocks#15]
Hi,
CircuitBlock V1.1.0 is crashing on my Macbook Pro : 

>  Model Name:	MacBook Pro
>   Model Identifier:	MacBookPro16,1
>   Processor Name:	6-Core Intel Core i7
>   Processor Speed:	2,6 GHz
>   Number of Processors:	1
>   Total Number of Cores:	6
>   L2 Cache (per Core):	256 KB
>   L3 Cache:	12 MB
>   Hyper-Threading Technology:	Enabled
>   Memory:	16 GB
>   Boot ROM Version:	1037.147.1.0.0 (iBridge: 17.16.16065.0.0,0)

Here's the crash report (happens immediately on startup) : 

> Uncaught Exception:
> Error: dlopen(/var/folders/pq/wgydqswj47g8_0cgrf12zvwh0000gn/T/.com.circuitmess.circuitblocks.B9JAUg, 1): no suitable image found.  Did find:
> 	/var/folders/pq/wgydqswj47g8_0cgrf12zvwh0000gn/T/.com.circuitmess.circuitblocks.B9JAUg: code signature in (/var/folders/pq/wgydqswj47g8_0cgrf12zvwh0000gn/T/.com.circuitmess.circuitblocks.B9JAUg) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
> 	/var/folders/pq/wgydqswj47g8_0cgrf12zvwh0000gn/T/.com.circuitmess.circuitblocks.B9JAUg: stat() failed with errno=17
>     at process.func (electron/js2c/asar.js:138:31)
>     at process.func [as dlopen] (electron/js2c/asar.js:138:31)
>     at Object.Module._extensions..node (internal/modules/cjs/loader.js:828:18)
>     at Object.func (electron/js2c/asar.js:138:31)
>     at Object.func [as .node] (electron/js2c/asar.js:147:18)
>     at Module.load (internal/modules/cjs/loader.js:645:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:560:12)
>     at Module.require (internal/modules/cjs/loader.js:685:19)
>     at require (internal/modules/cjs/helpers.js:16:16)
>     at bindings (/Applications/CircuitBlocks.app/Contents/Resources/app.asar/node_modules/bindings/bindings.js:112:48)

Don't hesitate if you need more info !

**Comment by filipbudisa** [comment]
Hello, Nicolas!
Thanks for the report. We are working on a fix for this and will publish it with the next update, which should land in the following weeks. I'll let you know via this issue when it's released.

Filip

**Comment by NicolasDucom** [comment]
Thanks ! Also realised I forgot to add I'm running Catalina Version 10.15.6 👍

**Comment by filipbudisa** [comment]
Hey again!
Just letting you know we published a release that we hope fixes the issue. You can download it on the [releases page](https://github.com/CircuitMess/CircuitBlocks/releases/tag/v1.1.1). Please let us know if this fixes you issue

Filip

**Comment by NicolasDucom** [comment]
Hi Filip ! 
Thanks for your message, I can confirm the fix works :)
