### ISSUE TITLE
More Details for Development Enviros

### ISSUE THREAD

**Issue by myue4github** [CircuitMess/CircuitBlocks#16]
Is it possible to provide more details on setting up a development environment? I tried using Ubuntu and Electron and failed. I get Node mismatches when attempting to build.

**Comment by filipbudisa** [comment]
Hello,
Currently we're pretty booked developing our first STEM Box product - Spencer, but in a few weeks we'll be free and will be spending more time polishing CircuitBlocks, which includes writing up a more detailed build guide.

In the meantime, node missmatches usually means the built native modules aren't compiled for the same version of node you are running. You can rebuild them by issuing the command ```yarn electron-rebuild``` in both the root directory and the client directory to build them for the electron back-end and the client front-end. Don't forget to run ```yarn``` in both directories before rebuilding to fetch the latest versions of modules. Be aware though that the rebuild can take some time to finish.

For rebuilding the modules, you will probably need to install some build tools. Specifically, a C/C++ compiler, python, and node-gyp.
You can install the compiler and python with ```sudo apt install build-essential python2.7 python3``` and node-gyp with ```npm install -g node-gyp```.

Let me know if you need any more help.

I would just like to ask you to use our [Contact & Support email](mailto:contact@circuitmess.com) for support, problems, help with building, etc. so we can keep the github page clean for bugs and code issues. Thanks!

Filip

**Comment by filipbudisa** [comment]
Hello. I've updated the readme in 7822b93. It now includes updated instructions on how to set up the dev environment and build the package
