### ISSUE TITLE
Usability: add tooltips to the toolbar buttons

### ISSUE THREAD

**Issue by andypiper** [CircuitMess/CircuitBlocks#17]
I had to read the tutorial to understand that CircuitBlocks has a built-in serial console monitor, and that what turns out to be the "export binary" button is running a compile in the background (it popped open a "save as" dialog on Windows, so I assumed at first that it would enable me to save my sketch to a location of my choosing, not compile it.

I think adding tooltips across the buttons would make the tool much more intuitive!

**Comment by filipbudisa** [comment]
Hello, thanks for the input. In a few weeks time we'll have a bit more time to polish up the interface and I'll make sure to include tooltips when we do that.

**Comment by filipbudisa** [comment]
Tooltips added in 6ada75b3e32da19568594966f274fb8da4db4b1b
