### ISSUE TITLE
Offline usage

### ISSUE THREAD

**Issue by andypiper** [CircuitMess/CircuitBlocks#18]
In the current version of CircuitBlocks (I'm running 1.2.1 on Windows 10), the IDE fails to load if there's no network connection, as it fails at the update check and there's no way to continue. If the network connection is restored while the app is still open, and the update check is retried, it then fails with an error about failing to connect to the Arduino Daemon.

I think autoupdate could become an optional preference, or silently ignored if the network is not available - this would enable users to get started more smoothly.

**Comment by filipbudisa** [comment]
Hello. The latest release allows running even if there is no internet connection present. You can find it on the releases page. Sorry for the inconvenience, it was a bit stupid to implement it the way it was before.
