### ISSUE TITLE
Community Discussions link goes to the Electron forum

### ISSUE THREAD

**Issue by bcorporaal** [CircuitMess/CircuitBlocks#20]
Currently (v 1.3.1 on Mac) the 'Community Discussions' link in the Help menu goes to the Electron forum. It would make more sense to have it link to the CircuitMess forum.

**Comment by filipbudisa** [comment]
Thanks for the heads up. None of us here at CircuitMess uses Macs and the only Mac we have is used only for compiling CircuitBlocks, so we didn't notice that. We'll address this issue in the next update.

**Comment by filipbudisa** [comment]
Fixed in fde391e, will be included in the next release (coming today)
