### ISSUE TITLE
yarn issue due to packagejson "sudo-prompt"

### ISSUE THREAD

**Issue by zdrascic** [CircuitMess/CircuitBlocks#21]
Since Text in Editor is too small i downloaded source to update UI and add some quality of life improvements in like font/text size ...

managed to install yarn, electron but have this strange issue when trying to install dependency pacakge 
`"sudo-prompt": "https://github.com/filipbudisa/sudo-prompt#add-env-to-options-type"`

this is the error i get

`Output:
remote: Repository not found.
fatal: repository 'https://github.com/filipbudisa/sudo-prompt/' not found`

is this repo private? can i replace it with some other?
also, what is policy on accepting 3rd party pull requests on open source project?

**Comment by filipbudisa** [comment]
Hello. At some point we had a PR active in the original sudo-prompt repo, and until it was merged I put a dependency in package.json to the forked repo. When the PR was merged I deleted the repo, but the dependency remained. I've updated the package.json now to use the original sudo-prompt package and everything should work now.

As far as 3rd party PRs are concerned, please go ahead. Any help we can get is appreciated :)

Cheers!
