### ISSUE TITLE
error with trigonometry functions

### ISSUE THREAD

**Issue by GasManGeek** [CircuitMess/CircuitBlocks#23]
When coding in blocks the trig functions convert angles specified in degrees in the block to angles in radians in the code. However the conversion factor is not correct. It should be: degrees*Pi/180, but the circuitblocks IDLE implements this as: degrees/180*Pi. See attached script in the blocks and my correction in the code version.

Found this as just got the nibble for my kid and he wanted to create an animation to rotate a sprite. So we were using some basic trig (sin and cos) functions to describe co-ordinates around a circle and the thing was giving bizarre results. Bit lucky I spotted the conversion error in the code - was about to give it up!

Win10 64bit version of circuit blocks
Nibble

![image](https://user-images.githubusercontent.com/82465181/114590319-82415a00-9c80-11eb-81e8-b2276d6e1652.png)

corrected code:
// cm:esp8266:nibble
#include <Arduino.h>
#include <CircuitOS.h>
#include <Nibble.h>

int x;
int y;
int rf;

Display* display;
Sprite* sprite;

void setup() {
  Nibble.begin();
  display = Nibble.getDisplay();
  sprite = display->getBaseSprite();

}

void loop() {
  x = 64;
  y = 32;
  rf = 15;
  for (int count = 0; count < 24; count++) {
    sprite->clear(TFT_WHITE);
    sprite->drawCircle(64, 64, 32, TFT_GREEN);
    sprite->fillCircle(x, y, 2, TFT_RED);
    display->commit();
    y = 32 * (1 - cos(rf * M_PI/ 180)) + 32;
    x = 32 * sin(rf * M_PI/ 180) + 64;
    rf = rf + 15;
    delay(42);
  }

}

**Comment by filipbudisa** [comment]
Thanks for letting us know about this. Fixed in 1ea76dc, will be included in next release (coming today)
