### ISSUE TITLE
Different issue on Chromebox attempted install of CircuitBlocks

### ISSUE THREAD

**Issue by LarvaRabbit** [CircuitMess/CircuitBlocks#25]
I saw an issue posted earlier about not being able to load CircuitBlocks on a Linux VM with Chrome OS.  I'm not real savvy with Linux, so not sure if this is a simple workaround or if its more complicated?  Also not entirely sure how to get the Linux version details?

Also tried the other APP, but could not find a way to run that as an .EXE, but will keep looking.  I have other options I can use, but this is the best computer for my kids to work on.

```
sudo dpkg -i /mnt/chromeos/MyFiles/Downloads/CircuitBlocks-1.7.1-Linux_x64.deb
(Reading database ... 34672 files and directories currently installed.)
Preparing to unpack .../CircuitBlocks-1.7.1-Linux_x64.deb ...
Unpacking circuitblocks (1.7.1) over (1.7.1) ...
dpkg: dependency problems prevent configuration of circuitblocks:
 circuitblocks depends on libnotify4; however:
  Package libnotify4 is not installed.
 circuitblocks depends on libnss3; however:
  Package libnss3 is not installed.
 circuitblocks depends on libappindicator3-1; however:
  Package libappindicator3-1 is not installed.
 circuitblocks depends on libsecret-1-0; however:
  Package libsecret-1-0 is not installed.

dpkg: error processing package circuitblocks (--install):
 dependency problems - leaving unconfigured
Processing triggers for desktop-file-utils (0.26-1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Errors were encountered while processing:
 circuitblocks
```

**Comment by filipbudisa** [comment]
Hello!

I'm afraid Chrome OS isn't supported by CircuitBlocks as the program requires dependencies not found in the ChromeOS package repositories. You can try to install them manually, but I'm not able to provide help with that. From the log you posted, the missing dependencies are lobnotify4, libnss3, libappindicator3-1, and libsecret-1-0

You could also try running the windows version of CircuitBlocks with Wine, but I doubt uploading sketches will work with that setup.

Best of luck,
Filip
