### ISSUE TITLE
Definition for rule '@typescript-eslint/no-angle-bracket-type-assertion' was not found

### ISSUE THREAD

**Issue by ihoru** [CircuitMess/CircuitBlocks#4]
How to solve this problem?

> client$ yarn build
> 
> yarn run v1.19.1
> $ node scripts/build.js
> Creating an optimized production build...
> Failed to compile.
> 
> ./src/layouts/Editor/components/Monaco.tsx
>   Line 1:  Definition for rule '@typescript-eslint/no-angle-bracket-type-assertion' was not found  @typescript-eslint/no-angle-bracket-type-assertion
> 
> Search for the keywords to learn more about each error.
> 
> 
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
>

**Comment by ihoru** [comment]
I got this on second trial:
![CircuitBlocks_245](https://user-images.githubusercontent.com/361908/67147607-73166180-f2c0-11e9-8ca3-bfbc6a2f0882.png)

**Comment by enastvo** [comment]
I'm receiving the same error when attempting to build with "yarn build" in Ubuntu 18.04. output as follows:

> yarn run v1.19.1
$ node scripts/build.js
Creating an optimized production build...
Failed to compile.

>./src/layouts/Editor/components/Monaco.tsx
  Line 1:  Definition for rule '@typescript-eslint/no-angle-bracket-type-assertion' was not found  @typescript-eslint/no-angle-bracket-type-assertion

>Search for the keywords to learn more about each error.


>error Command failed with exit code 1.

Am I missing something?

**Comment by filipbudisa** [comment]
Hey guys!

A conflict between some node packages arose a few days ago and we're working on resolving it as fast as we can. For now, you can bypass the error by commenting out or removing the tslint entry in client/config/webpack.config.js between the lines 312 and 326. Like so:
![Screenshot from 2019-10-21 21-27-53](https://user-images.githubusercontent.com/21333310/67236607-e1d2f680-f449-11e9-9e23-688cd6297735.png)

Cheers!

**Comment by filipbudisa** [comment]
The linter has been disabled in the latest release, so I'm closing this issue.

**Comment by filipbudisa** [comment]
The linter has been disabled in the latest release, so I'm closing this issue.

**Comment by filipbudisa** [comment]
The linter has been disabled in the latest release, so I'm closing this issue.

**Comment by filipbudisa** [comment]
The linter has been disabled in the latest release, so I'm closing this issue.

**Comment by filipbudisa** [comment]
The linter has been disabled in the latest release, so I'm closing this issue.

**Comment by filipbudisa** [comment]
The linter has been disabled in the latest release, so I'm closing this issue.

**Comment by filipbudisa** [comment]
The linter has been disabled in the latest release, so I'm closing this issue.
